name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm test -- --coverage  # создаст coverage/coverage-final.json

      - name: Upload coverage to SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=YOUR_GH_LOGIN_gendiff
            -Dsonar.organization=YOUR_SONARCLOUD_ORG
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
 
